name: Generate demo GIFs

on:
  workflow_dispatch:
  pull_request:

jobs:
  generate-gifs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: ss_15_tps_80
        uses: PabloLec/website-to-gif@develop
        with:
          url: "https://docs.github.com/en/get-started/quickstart/be-social"
          save_path: '/docs/images'
          file_format: webp
          file_name: ss_15_tps_80
          scroll_step: 15
          time_per_frame: 80
          window_width: 1280
          window_height: 720
      - name: ss_25_tps_100
        uses: PabloLec/website-to-gif@develop
        with:
          url: "https://docs.github.com/en/get-started"
          save_path: '/docs/images'
          file_name: ss_25_tps_100
          scroll_step: 25
          time_per_frame: 100
      - name: ss_50_tps_50
        uses: PabloLec/website-to-gif@develop
        with:
          url: "https://docs.github.com/en/get-started"
          save_path: '/docs/images'
          file_name: ss_50_tps_50
          scroll_step: 50
          time_per_frame: 50
      - name: ss_50_tps_100
        uses: PabloLec/website-to-gif@develop
        with:
          url: "https://docs.github.com/en/get-started"
          save_path: '/docs/images'
          file_name: ss_50_tps_100
          scroll_step: 50
          time_per_frame: 100
      - name: ss_50_tps_200
        uses: PabloLec/website-to-gif@develop
        with:
          url: "https://docs.github.com/en/get-started"
          save_path: '/docs/images'
          file_name: ss_50_tps_200
          scroll_step: 50
          time_per_frame: 200
      - name: animated_no_scroll
        uses: PabloLec/website-to-gif@develop
        with:
          url: "https://github.com/signup"
          save_path: "/docs/images"
          file_name: animated_no_scroll
          no_scoll: true
          time_per_frame: 100
          time_between_frames: 100
          number_of_frames: 50
          window_width: 1280
          window_height: 720
      - name: Archive GIFs
        uses: actions/upload-artifact@v4
        with:
          name: Generated GIFs
          path: |
            ./docs/images/*

  automerge-dependabot:
    runs-on: ubuntu-latest
    needs: generate-gifs
    if: github.actor == 'dependabot[bot]' && github.event.pull_request.user.login == 'dependabot[bot]' && github.event.pull_request.base.ref == 'develop'
    steps:
      - name: Enable auto-merge for Dependabot PRs
        run: gh pr merge --auto --merge "$PR_URL"
        env:
          PR_URL: ${{ github.event.pull_request.html_url }}
          GH_TOKEN: ${{ secrets.DEPENDABOT_TOKEN }}
          GITHUB_TOKEN: ${{ secrets.DEPENDABOT_TOKEN }}
