name: Update demo files

on:
  push:
    branches:
      - 'main'
  workflow_dispatch:

jobs:
  generate-gif:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: ss_15_tps_80
        uses: PabloLec/website-to-gif@dev
        with:
          url: "https://docs.github.com/en/get-started/quickstart/be-social"
          save_path: '/docs/images'
          file_format: gif
          file_name: ss_15_tps_80
          scroll_step: 15
          time_per_frame: 80
          window_width: 1280
          window_height: 720
      - name: ss_25_tps_100
        uses: PabloLec/website-to-gif@dev
        with:
          url: "https://docs.github.com/en/get-started/quickstart/be-social"
          save_path: '/docs/images'
          file_name: ss_25_tps_100
          scroll_step: 25
          time_per_frame: 100
          window_width: 1280
          window_height: 720
      - name: ss_50_tps_50
        uses: PabloLec/website-to-gif@dev
        with:
          url: "https://docs.github.com/en/get-started/quickstart/be-social"
          save_path: '/docs/images'
          file_name: ss_50_tps_50
          scroll_step: 50
          time_per_frame: 50
          window_width: 1280
          window_height: 720
      - name: ss_50_tps_100
        uses: PabloLec/website-to-gif@dev
        with:
          url: "https://docs.github.com/en/get-started/quickstart/be-social"
          save_path: '/docs/images'
          file_name: ss_50_tps_100
          scroll_step: 50
          time_per_frame: 100
          window_width: 1280
          window_height: 720
      - name: ss_50_tps_200
        uses: PabloLec/website-to-gif@dev
        with:
          url: "https://docs.github.com/en/get-started/quickstart/be-social"
          save_path: '/docs/images'
          file_name: ss_50_tps_200
          scroll_step: 50
          time_per_frame: 200
          window_width: 1280
          window_height: 720
      - name: Commit file to GH repo
        run: |
          git config --global user.name "PabloLec/website-to-gif"
          git config --global user.email "action@github.com"
          git add .
          git commit -m 'Update file'
          git push
